INSERT INTO FLIGHT_INVENTORY(ID, FLIGHT_NUMBER, ORIGIN, DESTINATION, DEPARTURE, CAPACITY, SEATS_BOOKED, UNIT_PRICE)
    VALUES(1, '100', 'AAA', 'BBB', '2025-04-28 15:30:00', 100, 3, 100);

INSERT INTO RESERVATION(ID, BOOKING_ID, SEAT_AMOUNT, AMOUNT_DUE, STATUS, FLIGHT_INVENTORY_ID)
    VALUES(1, 1, 3, 300, 'ACTIVE', 1);